#!/bin/bash

if [ -d /etc/php5/fpm ]; then
    CONF="/etc/php5/fpm/pool.d/webb.conf"
    RESTART="sudo service php5-fpm restart"
elif [ -d /etc/php/7.0/fpm ]; then
    CONF="/etc/php/7.0/fpm/pool.d/webb.conf"
    RESTART="sudo /etc/init.d/php7.0-fpm restart"
else
    echo "PHP FPM not found"
    exit 1
fi

sed "s/USER/$USER/g" php-fpm.conf > php-fpm.webb.conf
sudo mv -f php-fpm.webb.conf "$CONF"
$RESTART
