#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")" || exit 1

OPENRESTY_DIR="$PWD/../openresty"
WEBB_DIR="$PWD/www"
LUAPOWER_DIR="$PWD/../luapower"

[ "$(uname -m)" != x86_64 ] && P=linux32 || P=linux64

WEBBL="$DIR/$WEBB_DIR/?.lua"
LPB="$DIR/$LUAPOWER_DIR/bin/$P"
LPBL="$LPB/lua/?.lua"
LPBB="$LPB/clib/?.so"
LPL="$DIR/$LUAPOWER_DIR/?.lua"
ORL="$OPENRESTY_DIR/lualib/?.lua"
ORB="$OPENRESTY_DIR/lualib/?.so"
SYSB="/usr/local/lib"

export LUA_PATH="$WEBBL;$LPBL;$LPL;$ORL"
export LUA_CPATH="$LPBB;$ORB"
export LD_LIBRARY_PATH="$LPB:$SYSB"
export WEBB_DIR

exec "$OPENRESTY_DIR/nginx/sbin/nginx" -p "$PWD" -c "$PWD/nginx.conf" "$@"
