#!/bin/sh

OPENRESTY_DIR=/usr/local/openresty
WEBB_DIR=../www
LUAPOWER_DIR=../..

# ------------------------------------------------------------

DIR="$(dirname "$(readlink -f "$0")")"

[ "$ENV" ] || {
    [ -f ../env ] || { echo "../env file not found."; exit 1; }
    ENV=`cat ../env`
}
[ "$(uname -m)" != x86_64 ] && P=linux32 || P=linux64

WEBBL="$DIR/$WEBB_DIR/?.lua"
LPB="$DIR/$LUAPOWER_DIR/bin/$P"
LPBL="$LPB/lua/?.lua"
LPBB="$LPB/clib/?.so"
LPL="$DIR/$LUAPOWER_DIR/?.lua"
ORL="$OPENRESTY_DIR/lualib/?.lua"
ORB="$OPENRESTY_DIR/lualib/?.so"
SYSB="/usr/local/lib"

export LUA_PATH="$WEBBL;$LPBL;$LPL;$ORL"
export LUA_CPATH="$LPBB;$ORB"
export LD_LIBRARY_PATH="$LPB:$SYSB"

sudo -E "$OPENRESTY_DIR/nginx/sbin/nginx" -p "$DIR" \
    -c "$DIR/conf/nginx.$ENV.conf" "$@"
